apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../base
  - hpa.yaml
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: resources-patch.yaml
replicas:
  - name: api
    count: 2
  - name: worker
    count: 1
