apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../base
  - hpa.yaml
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: worker-resources-patch.yaml
  - path: mcp-github-resources-patch.yaml
  - path: worker-rollout-patch.yaml
  - path: api-rollout-patch.yaml
  - path: frontend-rollout-patch.yaml
  - path: mcp-test-analysis-rollout-patch.yaml
  - path: mcp-github-rollout-patch.yaml
replicas:
  - name: api
    count: 1
  - name: worker
    count: 1
